[package]
name = "invinembededicon"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = { version = "0.9.0", features = ["ksni"] }
png = "0.17.13"
